import fs from "fs/promises";
import path from "path";
import Pokedex from "pokedex-promise-v2";

import { pokemonConversion } from "@/lib/pokemon/conversion";
import {
  commentConstruct,
  DATA_PATH,
  rest,
  typescriptTypeConstruct,
} from "@/lib/pokemon/utils";

/**
 * Downloads Pokémon data from PokeAPI, processes them, and saves each Pokémon's data as a JSON file.
 * Each file is stored in the specified directory and named using the Pokémon's name.
 *
 * The method fetches a list of Pokémon, retrieves detailed data for each, and writes the data to a file.
 * Introduces a delay between API requests to prevent overwhelming the API server.
 *
 * This function is generally only ran once so we have an offline copy of PokeAPI's data. We will only ever need to
 * re-run this if we change the structure of the data. We use the downloaded data to seed our sqlite database on
 * app deployment.
 *
 * @return {Promise<void>} A promise that resolves when all Pokémon data has been successfully downloaded and saved.
 */
async function download(): Promise<void> {
  const P = new Pokedex();

  const pokemonNames = await P.getPokemonSpeciesList({ limit: 151 }).then(
    (res) => res.results.map((p) => p.name),
  );

  const pokemonSpeciesNames = new Set<string>();
  const pokemonFormNames = new Set<string>();

  for (const pokemonName of pokemonNames) {
    console.log(`Downloading ${pokemonName}...`);
    pokemonSpeciesNames.add(pokemonName);
    const pokemon = await pokemonConversion(P, pokemonName);

    await fs.writeFile(
      path.join(
        DATA_PATH,
        `pokemon/${pokemon.nationalDexNumber}-${pokemon.name}.json`,
      ),
      JSON.stringify(pokemon, null, 4),
    );

    for (const form of pokemon.forms) {
      pokemonFormNames.add(form.formName);
    }

    // Let's give PokeAPI a break
    await rest(500);
  }

  const pokemonSpeciesNameComment = commentConstruct(
    "AUTOGENERATED. This is a type union of all valid Pokemon species names. Do not modify this file directly.",
  );

  const pokemonSpeciesTypeUnion = typescriptTypeConstruct(
    "PokemonSpeciesName",
    Array.from(pokemonSpeciesNames),
  );

  const pokemonFormNameComment = commentConstruct(
    "AUTOGENERATED. This is a type union of all valid Pokemon form names. Do not modify this file directly.",
  );

  const pokemonFormsTypeUnion = typescriptTypeConstruct(
    "PokemonFormName",
    Array.from(pokemonFormNames),
  );

  await fs.writeFile(
    path.join(DATA_PATH, "pokemon/manifest.ts"),
    `${pokemonSpeciesNameComment}
    ${pokemonSpeciesTypeUnion}
    
    
    ${pokemonFormNameComment}
    ${pokemonFormsTypeUnion}`,
  );

  console.log("Done!");
}

download();
